# -*- coding: utf-8 -*-
"""Point Colection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tl9YiZtPsLIBypnajwIcn4Q4VNxQhtml
"""

import random

def generate_random_coordinates(num_points):
    coordinates = []
    for _ in range(num_points):
        latitude = random.uniform(-37.91, -37.71)  # -37.81 ± 0.1
        longitude = random.uniform(144.80, 145.00)  # 144.90 ± 0.1
        coordinates.append((latitude, longitude))
    return coordinates

num_points = 100
random_coordinates = generate_random_coordinates(num_points)

# Print the generated coordinates
for i, (lat, lon) in enumerate(random_coordinates, 1):
    print(f"Point {i}: Latitude = {lat}, Longitude = {lon}")